language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env: DJANGO_SETTINGS_MODULE=howtostoreiosdata.settings.dev
install: "pip install -r requirements/dev.txt --use-mirrors"
script: "python manage.py test"